version: '3'

services:
  example-service:
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 6001:6001
      - 9228:9228
    command: npm start

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
     - 43307:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
    
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
     - "8077:80" 



